# Generated by Django 5.2.17 on 2026-09-24 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('concern_type', models.CharField(choices=[('academic', 'Academic'), ('mental_health', 'Mental Health'), ('career', 'Career'), ('personal', 'Personal'), ('other', 'Other')], default='academic', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('counselor', 'Counselor'), ('student', 'Student'), ('receptionist', 'Receptionist')], db_index=True, default='student', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user_no', models.BigIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_no'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Encrypted ciphertext payload')),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='core.appointment')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='core.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_counselor', to='core.profile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_student', to='core.profile'),
        ),
        migrations.CreateModel(
            name='StudentMoodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_mood_alerts', to='core.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mood_alerts', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'is_active'], name='core_profil_role_bd4c58_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_no'], name='core_profil_user_no_1cdf27_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['student', '-created_at'], name='core_chatbo_student_0decfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='casenote',
            constraint=models.UniqueConstraint(fields=('appointment', 'counselor'), name='uniq_case_note_appt_counselor'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['student', 'scheduled_at'], name='core_appoin_student_5e2df2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['counselor', 'scheduled_at'], name='core_appoin_counsel_da197f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='core_appoin_status_e978b8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmoodalert',
            index=models.Index(fields=['counselor', '-created_at'], name='core_studen_counsel_9e1826_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmoodalert',
            index=models.Index(fields=['student', '-created_at'], name='core_studen_student_d59bdb_idx'),
        ),
    ]
